{% set name = "wakatime" %}
{% set version = "10.8.0" %}
{% set sha256 = "fa9abae5eea4c87cf81822854d31e8bd6ce25c7c89ef16cd35b74187d557bae8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - wakatime = wakatime.__init__:execute

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - wakatime

  commands:
    - wakatime --help

about:
  home: https://wakatime.com
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/wakatime/wakatime
  summary: 'Common interface to the WakaTime api.'

extra:
  recipe-maintainers:
    - proinsias
