{% set name = "wakatime" %}
{% set version = "10.1.3" %}
{% set sha256 = "7a9fd4cc7f6b14aac59e458752bffc64484df7cd131f05f8be59f47c643cd0fa" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - wakatime = wakatime.__init__:execute

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - wakatime

  commands:
    - wakatime --help

about:
  home: https://wakatime.com
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/wakatime/wakatime
  summary: 'Common interface to the WakaTime api.'

extra:
  recipe-maintainers:
    - proinsias
