{% set name = "wakatime" %}
{% set version = "13.0.0" %}
{% set sha256 = "9a96374be807baaea6a5b322eb1cc3b3e35294c5e62066181207b86a2fd46eac" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - wakatime = wakatime.__init__:execute

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - wakatime

  commands:
    - wakatime --help

about:
  home: https://wakatime.com
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/wakatime/wakatime
  summary: 'Common interface to the WakaTime api.'

extra:
  recipe-maintainers:
    - proinsias
