travis:
  secure:
    BINSTAR_TOKEN: DATgpuAHjIlkUYbx82/m9ZWCvIVXRJxPgaYAE9siWdLJdoMxtxmnaSZb3EZZOnbn0YEDfPRnjCtkvjfFhVoOfTa8CVv84CLvFR70VFONR3yPTd6QwWjimAJpS4x4vTdT3EjFTCq1IaB0EWDXg+DAdTC3jNNjAgz8sUJ4ShtBrOm3VrMlo7DG/6bsGQ9tHhk0GK7TAYmbZFfA4IcVJ1LHTFFnPtD9aKLaK5XfHw3FT/GdlYl+G2Dv8WuRi6yLZ/9/DklaG+Hfrsr/Y1ZckruEtfMx468OMT/LIEfowP2YDrqpFnk4xTC7JaUwaDAkO/vUb50es4LZDCG0u/2FaJMwsPv7ymubLdiynqZ9Ts4UR2HoD78Fsub3Y6qmenf7yB0K0WaPDb0DAJ5sxVt4D5TanQzt2MsLxfH/72xyFrjRUhtVB+1nfKZ+h+DNBK1XBsM0194s8JfF/GIcnMPbcegB6E7T8Qg4BhSpjS5HsJn6Q4/acB1bAGrwPv8+oekcI/pL1MIRTfdBVzX4zy3WTMYmLKXenf5WX5lQU3oBLfyEQG3Y5V646ROtyhRZz/SlSypbabPkZSrLfaeDgR2GtAMJqWQO0aXLddvbprc5LhokLuQG7T74/sAFRgVpZAqBvPYradpEYlX6/jnIwteYpk+7IctwzzYuYapf6JKzRgQcDf8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
